controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

deconnexion:
    path: /deconnexion
    controller: Symfony\Component\Security\Http\Logout\LogoutHandler
    methods: [POST]
